export const basicScopes = {
  RU_ColimScope_1: true,
  EN_ColimScope_1: true,
  EN_GoloScope_1: true,
  RU_X2Scope_1: true,
  EN_X2Scope_1: true,
  RU_X4Scope_1: true,
  EN_X4Scope_1: true,
  RU_X8Scope_1: true,
  EN_X8Scope_1: true,
};
export const uniqueAttachmentsToAlternatives: Record<string, string> = {
  UDP_Deadeye_Colim: "EN_ColimScope_1",
  Gun_Silence_ColimScope: "RU_ColimScope_1",
  Gun_Sledgehummer_GoloScope: "EN_GoloScope_1",
  Gun_Sotnyk_ColimScope: "RU_X2Scope_1",
  Sharpshooter_Silen: "EN_Silen_3",
  Gun_Silence_Silen: "RU_Silen_2",
  Sofmod_Silen: "EN_Silen_3",
  //GunDrowned_MagPaired: "GunAK_MagPaired", // removing crashes the game on existing save
  Gun_GStreet_MagIncreased: "GunM10_MagIncreased",
  // Gun_Shakh_MagIncreased: "GunViper_MagIncreased", // removing crashes the game on existing save
  GunPKP_Korshunov_MagLarge: "GunPKP_MagLarge",

  M701_Scope: "EN_X8Scope_1",
  M701_Colim_Scope: "EN_ColimScope_1",
  SVDM_Scope: "RU_X4Scope_1",
  Gvintar_Scope: "RU_X4Scope_1",
  SVU_Scope: "RU_X8Scope_1",
};

export const scopeDefinitions = {
  EN: {
    EN_GoloScope_1: {
      AttachPrototypeSID: "EN_GoloScope_1",
      Socket: "GoloScopeSocket",
      IconPosX: 155,
      IconPosY: 9,
    },
    EN_ColimScope_1: {
      AttachPrototypeSID: "EN_ColimScope_1",
      Socket: "ColimScopeSocket",
      IconPosX: 155,
      IconPosY: 9,
    },
    EN_X2Scope_1: {
      AttachPrototypeSID: "EN_X2Scope_1",
      Socket: "X2ScopeSocket",
      IconPosX: 155,
      IconPosY: 9,
      AimMuzzleVFXSocket: "X2ScopeMuzzle",
    },
    EN_X4Scope_1: {
      AttachPrototypeSID: "EN_X4Scope_1",
      Socket: "X4ScopeSocket",
      IconPosX: 60,
      IconPosY: 0,
      AimMuzzleVFXSocket: "X4ScopeMuzzle",
    },
    EN_X8Scope_1: {
      AttachPrototypeSID: "EN_X8Scope_1",
      Socket: "X8ScopeSocket",
      IconPosX: 60,
      IconPosY: 0,
      AimMuzzleVFXSocket: "X8ScopeMuzzle",
      AimShellShutterVFXSocket: "X8ScopeShells",
    },
  },
  nEN: {
    RU_ColimScope_1: {
      AttachPrototypeSID: "RU_ColimScope_1",
      Socket: "ColimScopeSocket",
      IconPosX: 155,
      IconPosY: 9,
    },
    RU_X2Scope_1: {
      AttachPrototypeSID: "RU_X2Scope_1",
      Socket: "X2ScopeSocket",
      IconPosX: 155,
      IconPosY: 9,
      AimMuzzleVFXSocket: "X2ScopeMuzzle",
      AimShellShutterVFXSocket: "X2ScopeShells",
    },
    RU_X4Scope_1: {
      AttachPrototypeSID: "RU_X4Scope_1",
      Socket: "X4ScopeSocket",
      IconPosX: 60,
      IconPosY: 0,
      AimMuzzleVFXSocket: "X4ScopeMuzzle",
      AimShellShutterVFXSocket: "X4ScopeShells",
    },
    RU_X8Scope_1: {
      AttachPrototypeSID: "RU_X8Scope_1",
      Socket: "X8ScopeSocket",
      IconPosX: 60,
      IconPosY: 0,
      AimMuzzleVFXSocket: "X8ScopeMuzzle",
    },
  },
};

export const basicAttachments = {
  ...basicScopes,
  RU_Silen_1: true,
  RU_Silen_2: true,
  RU_Silen_3: true,
  EN_Silen_1: true,
  EN_Silen_2: true,
  EN_Silen_3: true,
  EN_Silen_4: true,
  GunPM_MagIncreased: true,
  GunUDP_MagIncreased: true,
  GunM10_MagIncreased: true,
  GunAPB_MagIncreased: true,
  GunKora_MagIncreased: true,
  GunViper_MagIncreased: true,
  GunAK_MagPaired: true,
  GunBucket_MagIncreased: true,
  GunIntegral_MagIncreased: true,
  GunZubr_MagIncreased: true,
  GunAK74_MagIncreased: true,
  GunM16_MagIncreased: true,
  GunGP37_MagPaired: true,
  GunGP37_MagLarge: true,
  GunFora_MagIncreased: true,
  GunGrim_MagIncreased: true,
  GunGrim_MagLarge: true,
  GunGvintar_MagIncreased: true,
  GunKharod_MagPaired: true,
  GunLavina_MagIncreased: true,
  GunDnipro_MagPaired: true,
  GunPKP_MagIncreased: true,
  GunPKP_MagLarge: true,
  GunM860_MagLarge: true,
  GunD12_MagIncreased: true,
  GunD12_MagPaired: true,
  GunD12_MagLarge: true,
  GunMark_MagIncreased: true,
  GunSVU_MagIncreased: true,
  GunGauss_MagIncreased: true,
  RU_GLaunch_1: true,
  EN_GLaunch_1: true,
  EN_BuckLaunch_1: true,
};
